---
#
# Tasks and roles for all hosts
#
- hosts: mona
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml
        tags:
            - always
            - port

- hosts: fleet
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: avahi
        tags:
            - avahi

      - role: geerlingguy.security
        tags:
            - security

      - role: geerlingguy.docker
        tags:
            - docker

      - name: containers
        tags:
          - containers

      - role: tailscale
        when: tailscale_enabled | default(false)
        tags:
            - tailscale
