#
# Packages
#
extra_packages:
  - fish
  - iperf3
  - speedtest-cli
  - htop
  - stow
  - eza
  - git
  - neofetch
  - neovim
  - tmux
  - mosh
  - rsync
  - openjdk-25-jdk-headless
  - lm-sensors
  - iotop
  - ncdu
